# Generated by Django 3.1.2 on 2020-10-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_type', models.CharField(choices=[('PC', 'POCO X3'), ('RLME', 'Realme Narzo 20'), ('ETEL', 'Ecotel E17'), ('RD9', 'Redmi 9i'), ('INFS4', 'Infinix Smart 4 Plus')], default='PC', max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
