# Generated by Django 3.1.2 on 2020-10-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201002_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='description',
            new_name='Hightlights',
        ),
    ]
