# Generated by Django 3.1.2 on 2020-10-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201004_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='Hightlights',
            new_name='Highlights',
        ),
    ]
